### Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
### Libraries USed Tensorflow> 2.0  and keras

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [ ]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
### sentences
sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [ ]:
sent

['The world is a better place',
 'Marvel series is my favourite movie',
 'I like DC movies',
 'the cat is eating the food',
 'Tom and Jerry is my favourite movie',
 'Python is my favourite programming language']

In [ ]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[293, 261, 306, 193, 243, 360], [180, 36, 306, 405, 158, 356], [480, 227, 155, 253], [293, 311, 306, 234, 293, 316], [133, 111, 306, 306, 405, 158, 356], [223, 306, 405, 158, 51, 401]]


### Word Embedding Represntation

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [ ]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0 293 261 306 193 243 360]
 [  0   0 180  36 306 405 158 356]
 [  0   0   0   0 480 227 155 253]
 [  0   0 293 311 306 234 293 316]
 [  0 133 111 306 306 405 158 356]
 [  0   0 223 306 405 158  51 401]]


In [ ]:
## 10 feature dimesnions
dim=10


In [ ]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0, 293, 261, 306, 193, 243, 360], dtype=int32)

In [ ]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step


array([[-0.0318832 ,  0.01504428, -0.04673633, -0.02505848,  0.04471124,
         0.02067688,  0.04791081,  0.01671721, -0.04096345,  0.02523002],
       [-0.0318832 ,  0.01504428, -0.04673633, -0.02505848,  0.04471124,
         0.02067688,  0.04791081,  0.01671721, -0.04096345,  0.02523002],
       [ 0.03072243,  0.04608629,  0.01468945,  0.02701337, -0.04292427,
         0.04773084,  0.0144798 , -0.03439845, -0.03700626, -0.03199706],
       [ 0.0200357 ,  0.04016082, -0.04157149, -0.00278394, -0.03870435,
         0.01881749,  0.02867384,  0.01314812,  0.00113349, -0.00599526],
       [ 0.01191788,  0.04291494,  0.02737426,  0.0130191 ,  0.00010514,
        -0.04553268, -0.01524724, -0.04223355, -0.02868136, -0.00467823],
       [ 0.02444369,  0.03429883,  0.02375574, -0.01111213, -0.03697998,
        -0.02019721,  0.00817977,  0.04614351, -0.02227749,  0.02232969],
       [ 0.0042884 ,  0.03855807, -0.04285327,  0.00633978, -0.04964188,
        -0.01192137,  0.01260451, -0.0004751 

In [ ]:
print(model.predict(embedded_docs[0]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
[[-0.0318832   0.01504428 -0.04673633 -0.02505848  0.04471124  0.02067688
   0.04791081  0.01671721 -0.04096345  0.02523002]
 [-0.0318832   0.01504428 -0.04673633 -0.02505848  0.04471124  0.02067688
   0.04791081  0.01671721 -0.04096345  0.02523002]
 [ 0.03072243  0.04608629  0.01468945  0.02701337 -0.04292427  0.04773084
   0.0144798  -0.03439845 -0.03700626 -0.03199706]
 [ 0.0200357   0.04016082 -0.04157149 -0.00278394 -0.03870435  0.01881749
   0.02867384  0.01314812  0.00113349 -0.00599526]
 [ 0.01191788  0.04291494  0.02737426  0.0130191   0.00010514 -0.04553268
  -0.01524724 -0.04223355 -0.02868136 -0.00467823]
 [ 0.02444369  0.03429883  0.02375574 -0.01111213 -0.03697998 -0.02019721
   0.00817977  0.04614351 -0.02227749  0.02232969]
 [ 0.0042884   0.03855807 -0.04285327  0.00633978 -0.04964188 -0.01192137
   0.01260451 -0.0004751   0.03391742 -0.03861283]
 [ 0.04352913  0.00994565  0.03231429  0.04131201  0.00625808  0.00282208
  -0.02945832

In [ ]:
embedded_docs[0]

array([  0,   0, 293, 261, 306, 193, 243, 360], dtype=int32)

In [ ]:
print(model.predict(embedded_docs[0]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
[[-0.0318832   0.01504428 -0.04673633 -0.02505848  0.04471124  0.02067688
   0.04791081  0.01671721 -0.04096345  0.02523002]
 [-0.0318832   0.01504428 -0.04673633 -0.02505848  0.04471124  0.02067688
   0.04791081  0.01671721 -0.04096345  0.02523002]
 [ 0.03072243  0.04608629  0.01468945  0.02701337 -0.04292427  0.04773084
   0.0144798  -0.03439845 -0.03700626 -0.03199706]
 [ 0.0200357   0.04016082 -0.04157149 -0.00278394 -0.03870435  0.01881749
   0.02867384  0.01314812  0.00113349 -0.00599526]
 [ 0.01191788  0.04291494  0.02737426  0.0130191   0.00010514 -0.04553268
  -0.01524724 -0.04223355 -0.02868136 -0.00467823]
 [ 0.02444369  0.03429883  0.02375574 -0.01111213 -0.03697998 -0.02019721
   0.00817977  0.04614351 -0.02227749  0.02232969]
 [ 0.0042884   0.03855807 -0.04285327  0.00633978 -0.04964188 -0.01192137
   0.01260451 -0.0004751   0.03391742 -0.03861283]
 [ 0.04352913  0.00994565  0.03231429  0.04131201  0.00625808  0.00282208
  -0.02945832